# -*- coding: utf-8 -*-
"""SigmoidalPythonDoZeroAnlisandoEmpresa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_h0VAe8C5IRGFiv-UL1e7SiAkRmG8WGw
"""

#importar  a biblioteca pandas(ver cocneitos e pensar no artigo)
#abaixo importamos com apelido para que nao tenha que digitar pandas
import pandas as pd

#para salvar o dataseset - selecionar arquivo e arrastar para o lado esquerdo e depois co botao direito copiar arquivo

#carregar o dataset, porem da formula simples como abaixo so aparece uma aba. Para carregar tudo 
#planilha = pd.read_excel('/content/controle_da_empresa.xlsx')
#coloque o None e pelo menos carrega as abas
planilha = pd.read_excel('/content/controle_da_empresa.xlsx',None)

planilha

#Carrega somente a aba estoque
planilha["Estoque"]

#Carrega somente a aba estoque
planilha["Vendas"]

#Carrega somente a aba estoque
planilha["Funcionários"]

#Caso queiramos ver as abas sem ter de abrir excel
planilha.keys()

#Agora vamos soma o Total de vendas  - Somar uma coluna
#primeiro informa a variavel que recebeu o dataset - planilha
#segundo selecionar a aba - vendas
#terceiro selecionar a coluna - total de vendas
#implementar a funcao sum ou qual funcação queiser agregar a coluna - sum()
planilha["Vendas"]["Total de Vendas"].sum()

#Agora vamos a media de  Total de vendas  - Media da coluna
#primeiro informa a variavel que recebeu o dataset - planilha
#segundo selecionar a aba - vendas
#terceiro selecionar a coluna - total de vendas
#implementar a funcao mean ou qual funcação queiser agregar a coluna - mean()
planilha["Vendas"]["Total de Vendas"].mean()

#Agora vamos ao desvio padrao  Total de vendas  - desvio padrai da coluna
#primeiro informa a variavel que recebeu o dataset - planilha
#segundo selecionar a aba - vendas
#terceiro selecionar a coluna - total de vendas
#implementar a funcao std ou qual funcação queiser agregar a coluna - std()
planilha["Vendas"]["Total de Vendas"].std()

#Agora criar um grafico com o dataset excel
# para nao ter que ficar apontadndo para planilha["Vendas"], crio uma varivel atalho e jogo
vendas = planilha["Vendas"]
#na variavel venda que criei recebendo a aba vendas , plotei os dados onde x é a data da venda e y o total de vendas
vendas.plot("Data da Venda","Total de Vendas")

#Agora criar um histrograma para verificar as vendas
#criei um histograma que gera total vendas 
vendas.hist("Total de Vendas")



"""Agra vamos visualizar um histograma para verificar as vendas por dia de semana.
precisamremos usaar uma funcao lambda
CONCEITO DO LIVRO PYTHON PARA ANALISE DE DADOS SOBRE LAMBDA
      ###  Python oferece suporte para funcções que sao chamdas de funcçõe slmabdas ou anonimas
      ###, que e uma forma de escrverver funcções consituidas de uma unica instrução cujo resultado
      ### e o valor retornado
      
      Função Comum:
      def sorteio(x):
        return x*2

      Funcao Lambda:
      lambda x: x *2
"""

vendas['Data da Venda'].apply(lambda x:x.weekday()).hist(bins=7)